name: Style Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatter:
    name: Run black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
